### ISSUE TITLE
[List] Initial Required List of Changes

### ISSUE THREAD

**Issue by devAyushDubey** [RyanWalker277/InnohacksWebsite#1]
### Frontend Tasks
- [ ] **Navbar** changes according to Innohacks 2023
- [ ] Static Header Background to Dynamic
- [ ] Code of Conduct Page
- [ ] Social Media Links
- [ ] Speaker Section
- [ ] Content of **About** section
- [ ] Content of **Timeline** section
- [ ] Content of **Judges** section
- [ ] Content of **Mentor** section
- [ ] Content of **Workshop/ Bootcamp** section
- [ ] Content of **Sponsor** section
- [ ] **About Club**
- [ ] Footer Changes
- [ ] **Our Team** corousel

Suggest all the other changes in replies so that I can list them here.

**Comment by RyanWalker277** [comment]
@devAyushDubey other changes will be added on the go, this checklist looks fine to me for now. @Tejash11 will be working on these for now.

**Comment by Tejash11** [comment]
> @devAyushDubey other changes will be added on the go, this checklist looks fine to me for now. @Tejash11 will be working on these for now.
yeah sure
